import { useMemo, useRef } from "react";
import "./App.css";
import { ZoneCard } from "./ZoneCard";
import { useDashboardSocket } from "./useDashboardSocket";
import type { Alert, OccupancyPoint } from "./types";

const HISTORY_LENGTH = 40; // ~40 broadcasts (roughly 40s at the default 1s interval)
const ACTIVE_ALERT_WINDOW_MS = 8000; // how long a zone stays highlighted after its last alert

/**
 * How recently a zone's latest alert was first *observed by this browser*,
 * keyed by zone. Deliberately does NOT compare the alert's own embedded
 * `timestamp` (generated by the producer/processor containers) against the
 * browser's `Date.now()` -- those can run on different hosts/VMs (e.g. a
 * Docker Desktop VM vs. the host machine) whose clocks are not guaranteed
 * to be in sync, which would make a just-arrived alert look "stale"
 * (or even "in the future") purely from clock skew. Instead we stamp each
 * alert with the browser's own clock the first time we see it, so
 * "how long has this been active" is measured entirely client-side.
 */
type SeenAlert = { alertKey: string; seenAtMs: number };

function alertKeyFor(alert: Alert): string {
  return `${alert.zone}@${alert.timestamp}`;
}

/** Most recent alert per zone, from the newest-first `snapshot.alerts` list. */
function latestAlertByZone(alerts: Alert[]): Map<string, Alert> {
  const byZone = new Map<string, Alert>();
  for (const alert of alerts) {
    if (!byZone.has(alert.zone)) {
      byZone.set(alert.zone, alert);
    }
  }
  return byZone;
}

export default function App() {
  const { snapshot, status } = useDashboardSocket("/ws");
  const historyRef = useRef<Map<string, OccupancyPoint[]>>(new Map());
  const seenAlertsRef = useRef<Map<string, SeenAlert>>(new Map());

  const alertsByZone = useMemo(
    () => latestAlertByZone(snapshot?.alerts ?? []),
    [snapshot],
  );

  // Record, in the browser's own clock, the first time we observe each
  // zone's latest alert -- see the `SeenAlert` comment above for why.
  if (snapshot) {
    for (const [zone, alert] of alertsByZone) {
      const key = alertKeyFor(alert);
      const existing = seenAlertsRef.current.get(zone);
      if (existing?.alertKey !== key) {
        seenAlertsRef.current.set(zone, { alertKey: key, seenAtMs: Date.now() });
      }
    }
  }

  const isZoneActive = (zone: string): boolean => {
    const seen = seenAlertsRef.current.get(zone);
    return seen !== undefined && Date.now() - seen.seenAtMs < ACTIVE_ALERT_WINDOW_MS;
  };

  const activeAlerts = useMemo(
    () => [...alertsByZone.entries()].filter(([zone]) => isZoneActive(zone)).map(([, a]) => a),
    // eslint-disable-next-line react-hooks/exhaustive-deps -- also depends on seenAlertsRef mutations above
    [alertsByZone],
  );

  const zoneNames = useMemo(
    () => Object.keys(snapshot?.zones ?? {}).sort(),
    [snapshot],
  );

  // Update the rolling per-zone history in place (a ref, not state) so we
  // don't re-render twice per snapshot; the snapshot state update below
  // already triggers the re-render that picks up these mutations.
  if (snapshot) {
    for (const zone of zoneNames) {
      const latest = snapshot.zones[zone].latest;
      if (!latest) continue;
      const existing = historyRef.current.get(zone) ?? [];
      const last = existing[existing.length - 1];
      if (last?.time === latest.timestamp) continue; // no new reading since last snapshot

      const hasAlert = alertsByZone.get(zone)?.timestamp === latest.timestamp;
      const next = [
        ...existing,
        {
          time: latest.timestamp,
          occupancy: latest.occupancy,
          isAnomaly: hasAlert,
        },
      ].slice(-HISTORY_LENGTH);
      historyRef.current.set(zone, next);
    }
  }

  return (
    <div className="app">
      <header className="app__header">
        <div>
          <h1>Zone Occupancy Dashboard</h1>
          <p className="app__subtitle">
            Live rolling occupancy, Welford mean/std, and Z-score anomaly alerts per zone.
          </p>
        </div>
        <div className={`status status--${status}`}>
          <span className="status__dot" />
          {status === "live" ? "live" : status === "connecting" ? "connecting…" : "disconnected, retrying…"}
        </div>
      </header>

      <section className={`alerts-banner ${activeAlerts.length > 0 ? "alerts-banner--active" : ""}`}>
        {activeAlerts.length === 0 ? (
          <span>All zones within normal range.</span>
        ) : (
          <>
            <strong>{activeAlerts.length} zone{activeAlerts.length > 1 ? "s" : ""} anomalous:</strong>
            {activeAlerts.map((a) => (
              <span className="alerts-banner__item" key={a.zone}>
                {a.zone} (|z|={Math.abs(a.z_score).toFixed(2)})
              </span>
            ))}
          </>
        )}
      </section>

      {!snapshot ? (
        <div className="empty-state">Waiting for data from the stream processor…</div>
      ) : (
        <>
          <section className="zone-grid">
            {zoneNames.map((zone) => (
              <ZoneCard
                key={zone}
                zone={zone}
                snapshot={snapshot.zones[zone]}
                history={historyRef.current.get(zone) ?? []}
                activeAlert={isZoneActive(zone) ? alertsByZone.get(zone)! : null}
              />
            ))}
          </section>

          <section className="alert-log">
            <h2>Recent alerts</h2>
            {snapshot.alerts.length === 0 ? (
              <p className="empty-state empty-state--inline">No anomalies detected yet.</p>
            ) : (
              <table>
                <thead>
                  <tr>
                    <th>Time</th>
                    <th>Zone</th>
                    <th>Occupancy</th>
                    <th>Z-score</th>
                    <th>Reason</th>
                  </tr>
                </thead>
                <tbody>
                  {snapshot.alerts.slice(0, 20).map((alert, i) => (
                    <tr key={`${alert.zone}-${alert.timestamp}-${i}`}>
                      <td>{new Date(alert.timestamp).toLocaleTimeString()}</td>
                      <td>{alert.zone}</td>
                      <td>{alert.occupancy}</td>
                      <td>{alert.z_score}</td>
                      <td>{alert.reason}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </section>
        </>
      )}
    </div>
  );
}
